name: Checker

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: check dotfiles
      run: sh init.sh
