name: Checker

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: check folder structure
      run: ls -al

    - name: check shell script
      run: echo Hello, world!
